### ISSUE TITLE
Training on Java snippets

### ISSUE THREAD

**Issue by kevinGit777** [eth-sri/TFix#1]
Hi, 
I love your work so much! It is simple yet powerful. I need some help with training my own model. My dataset consists of some Java code sinippets. Could you give me a guide on how to modify the code so it could train with only code snippets instead of error messages? 
Thank you so much!
Haifan Wu

**Comment by LostBenjamin** [comment]
Hi,

You need to set the argument `include_warning` to `False` for all appearance of function `GetT5Representation`. See [this line](https://github.com/eth-sri/TFix/blob/764c19b3ebd3ed6e20bbe9e6056979947e483dcd/data_reader.py#L52).

Best,
Jingxuan
