### ISSUE TITLE
Trying the tool

### ISSUE THREAD

**Issue by yehyaali151989** [eth-sri/TFix#15]
Hello Sir, I am trying to run your tool on my laptop but they gave me some errors,
could you please guide me on how to run and use TFix tool?

Thanks

**Comment by BBerabi** [comment]
Hi Yehya, 

I see that you closed the issue. I assume you fixed it. 

Let me know if I can help.

Best,
Berkay

**Comment by yehyaali151989** [comment]
Hi Dear,
No it is not solved  yet 
Please I need your help and if you can answer my messages on facebook.

**Comment by BBerabi** [comment]
I dont have any messages on FB.

Does your machine have a GPU?

**Comment by yehyaali151989** [comment]
No my machine doesn't have. 
What should I do please. 
check your request messages on fb.
