### ISSUE TITLE
Downloading dataset

### ISSUE THREAD

**Issue by mahdi943** [eth-sri/TFix#21]
Hello,
I am not able to download the dataset. I got the error: "Failed - Forbidden"
Could you please help me with that?

**Comment by BBerabi** [comment]
Hi @mahdi943 

I just tried it and it works for me. Could you elaborate more on the error you are getting and how you are trying to download the dataset? 

You can also share a screen recording.

Thank you!

**Comment by mahdi943** [comment]
> Hi @mahdi943
> 
> I just tried it and it works for me. Could you elaborate more on the error you are getting and how you are trying to download the dataset?
> 
> You can also share a screen recording.
> 
> Thank you!

Thank you for your reply. I solved my problem by switching off chrome accelerator.

**Comment by BBerabi** [comment]
Nice, glad to hear it! I am closing the issue as it is resolved.
