### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by mahdi943** [eth-sri/TFix#22]
Hello,

Here is the Runtime error when I try to run "tfix_testing.py":

RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.10 GiB already allocated; 0 bytes free; 3.10 GiB reserved in total by PyTorch)

I am using PC with NVIDIA Geforce GTX 1050 Ti

**Comment by ghost** [comment]
Hi @mahdi943, 

This is simply a memory error as it is stated in the error message. Your GPU does not have enough memory to fit the model and the batches. GTX 1050 Ti is relatively old GPU. 

If you do not have access to more powerful GPUs, you can try to reduce memory consumption by tweaking some parameters but there is no guarantee that this will be enough. Still, worth to try

- Switch to the smallest model: `t5-small`
- Reduce your `batch_size`. For example, set it to `1`
- Set `eval_accumulation_steps` to `1`. This will utilize CPU memory more frequently 

For details about the parameters, you can refer to the table in the README and also look it up in HuggingFace's documentation.

I hope this will help!

Best,
Berkay

**Comment by mahdi943** [comment]
Hi @bberabi11 

Thanks for your suggestion. Switching to t5-small worked. 

Mahdi

**Comment by ghost** [comment]
Happy to hear that you could solve the issue!  I am closing the issue :)

Good luck!
